version: '3.1'

services:
  main-service:
    image: 'aligator9/internship-main-service'
    container_name: 'internship-main-service-container'
    depends_on:
      - main-service-database
    ports:
      - "7070:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-service-database:5432/internship-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=almas0606
      - SPRINGDOC_API_DOCS_ENABLED=true
      - SPRINGDOC_SWAGGER_UI_ENABLED=true

  main-service-database:
    image: 'postgres'
    container_name: 'internship-database-container'
    ports:
      - "2345:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=almas0606
      - POSTGRES_DB=internship-db

  keycloak-service:
    image: 'aligator9/internship-keycloak-service'
    container_name: 'keycloak-service-container'
    depends_on:
      - keycloak
    ports:
      - "7071:8001" 
    environment:
      - SERVER_PORT=8001
      - SPRINGDOC_API_DOCS_ENABLED=true
      - SPRINGDOC_SWAGGER_UI_ENABLED=true
      - keycloak.url=http://keycloak:8080/auth
      - keycloak.realm=bitlab
      - keycloak.client-id=internship-client
      - keycloak.client-secret=secret-key-for-client
      - keycloak.username=almas06
      - keycloak.password=admin-password
      - keycloak.grant-type=password

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    container_name: 'keycloak-container'
    environment:
      KC_DB: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_URL: jdbc:postgresql://keycloak-db/keycloakdb
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    command: ["start-dev", "--http-relative-path=/auth", "--import-realm"]
    ports:
      - "8081:8080"
      - "8843:8443"
    volumes:
      - ../keycloak-service/bitlab-realm.json:/opt/keycloak/data/import/bitlab-realm.json
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloakdb
    ports:
      - "2347:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


